services:
  pocketbase:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    env_file:
      - .env
    volumes:
      - pocketbase_data:/app/pb_data
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:8090/api/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # sets the defaults on pocketbase
  pocketbase-init:
    build:
      context: ./db
      dockerfile: Dockerfile.init
    depends_on:
      pocketbase:
        condition: service_healthy
    env_file:
      - .env
    restart: 'no'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_POCKETBASE_URL=http://pocketbase:8090
    env_file:
      - .env
    depends_on:
      pocketbase:
        condition: service_healthy
      pocketbase-init:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  pocketbase_data:
